services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./web/html:/var/www/html
      - ./web/nginx.conf:/etc/nginx/nginx.conf
      - ./letsencrypt:/etc/letsencrypt
    depends_on:
      - php
    networks:
      - dmz

  php:
    build: ./php
    image: php:custom
    container_name: php
    volumes:
      - ./web/html:/var/www/html
    depends_on:
      - mariadb
    env_file:
      - ./db/db.env
    networks:
      - dmz
      - db_net

  mariadb:
    image: mariadb:latest
    container_name: mariadb
    env_file:
      - ./db/db.env
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
      - ./db/data:/var/lib/mysql
      - ./db/my-resolve.cnf:/etc/mysql/conf.d/my-resolve.cnf
    networks:
      - db_net

  dns:
    image: internetsystemsconsortium/bind9:9.18
    container_name: dns
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    volumes:
      - ./dnsConfig/named.conf:/etc/bind/named.conf
      - ./dnsConfig/l1-20.ephec-ti.be.zone:/etc/bind/l1-20.ephec-ti.be.zone
      - ./dnsConfig/l1-20.ephec-ti.be.zone.signed:/etc/bind/l1-20.ephec-ti.be.zone.signed
    networks:
      - dmz
    environment:
      - TZ=Europe/Brussels
    restart: unless-stopped

networks:
  dmz:
  db_net:
